language: node_js
node_js:
  - node
before_script:
  - 'git config --global user.name "Travis CI"'
  - 'git config --global user.email "imjaroiswebdev@gmail.com"'
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    branch: site-src
